SELECT
TRIM(B1_COD) B1_COD,
TRIM(B1_GRUPO) B1_GRUPO,
TRIM(B1_UM) B1_UM,
TRIM(B1_DESC) B1_DESC,
TRIM(NNR_DESCRI) NNR_DESCRI
FROM SB1010 SB1
RIGHT JOIN NNR010 NNR
ON NNR.NNR_CODIGO = SB1.B1_LOCPAD AND NNR.D_E_L_E_T_ = ''
WHERE SB1.D_E_L_E_T_ = '' AND B1_ATIVO = 'S' AND B1_MSBLQL = '2' AND B1_GRUPO NOT IN ('9999', '0000')
ORDER BY B1_COD ASC


