SELECT SD1.D1_FILIAL FILIAL, SD1.D1_CC CCUSTO, CTT.CTT_DESC01 DESCCCUSTO, SD1.D1_PEDIDO PEDIDO, SD1.D1_COD PRODUTO, SB1.B1_UM UM, SB1.B1_DESC DESCPROD, SD1.D1_QUANT QTDE, SD1.D1_VUNIT VALUNIT,   
SD1.D1_TOTAL VALBRUTO, ((SD1.D1_TOTAL + SD1.D1_VALIPI + SD1.D1_DESPESA) - SD1.D1_VALDESC) VALLIQUIDO, SE2.E2_FILIAL FILSE2, SE2.E2_PREFIXO PREFIXO, SE2.E2_NUM TITULO, SE2.E2_PARCELA PARCELA, SE2.E2_TIPO TIPO, SE2.E2_FORNECE FORNECE, SE2.E2_LOJA LOJA,    
SE2.E2_NOMFOR NOMFOR, SA2.A2_NOME NOME, SA2.A2_ZZDRE DRE, SD1.D1_EMISSAO DTEMISNF, SE2.E2_EMISSAO DTEMISTIT, SE2.E2_VENCTO DTVENCTO, SE2.E2_BAIXA DTBAIXA, SE2.E2_VALOR VALTITULO, SE2.E2_HIST HISTORICO, SD1.D1_ZZUSER USUARIO, SE2.E2_USERLGI USERLGI,  
CASE WHEN SA2.A2_MSBLQL = 1 THEN 'Sim' ELSE 'Não' END AS BLOQUEADO
FROM SD1010 SD
INNER JOIN SE2010 SE2 ON SE2.E2_FILIAL = SD1.D1_FILIAL AND SE2.E2_NUM = SD1.D1_DOC AND SE2.E2_FORNECE = SD1.D1_FORNECE AND SE2.E2_LOJA = SD1.D1_LOJA AND SE2.D_E_L_E_T_ = ' '   
INNER JOIN SB1010 SB1 ON SB1.B1_COD = SD1.D1_COD AND SB1.D_E_L_E_T_ = ' '   
INNER JOIN SA2010 SA2 ON SA2.A2_COD = SD1.D1_FORNECE AND SA2.A2_LOJA = SD1.D1_LOJA AND SA2.D_E_L_E_T_ = ' '
LEFT JOIN CTT010 CTT ON CTT.CTT_CUSTO = SD1.D1_CC AND CTT.D_E_L_E_T_ = ' ' 
WHERE SD1.D1_FILIAL BETWEEN '0101' AND '0120' 
AND SD1.D1_EMISSAO BETWEEN '"+cDataDe+"' AND '"+cDataAte+"' 
AND SD1.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO NOT IN('AGL', 'PMF')
ORDER BY SD1.D1_FILIAL  






